### ISSUE TITLE
Something related to OSX brew is broken on Travis

### ISSUE THREAD

**Issue by gcarreno** [nielsAD/travis-lazarus#10]
Hey there,

I'm using what you built here in [laz-qBitTorrent-WebUI](https://github.com/gcarreno/laz-qBitTorrent-WebUI).

I've had to remove all mentions of `osx` from [`.travis.install.py`](https://github.com/gcarreno/laz-qBitTorrent-WebUI/blob/master/.travis.install.py) and [`.travis.yml`](https://github.com/gcarreno/laz-qBitTorrent-WebUI/blob/master/.travis.yml) because it was giving an error when dealing with it.

Hope you can reproduce. If not I'll provide my error reports.

Cheers,
Gus

**Comment by nielsAD** [comment]
When using `LAZ_PKG=true` on OSX, Homebrew will download the release from SourceForge. Sometimes this will result in 10 minutes without console output, which will cause Travis to kill the build. I'm not sure if this is related to the network speed of the OSX machines or SourceForge. Restarting the build will usually solve the problem.

**Comment by gcarreno** [comment]
Hi there,

I've restarted this job [osx LAZ_PKG=true](https://travis-ci.org/gcarreno/laz-qBitTorrent-WebUI/jobs/208346450) once and I'm waiting for it to run again since it errored out the second time.

Hope 3 times the charm.

If you look at it, is it the problem you were talking about? Cuz there some errors on the X11 side also.

Cheers,
Gus

**Comment by gcarreno** [comment]
Hi Niels,

The third time was the one that made it. So I'll close this issue.

Never the less I'll omit OSX in my builds for the foreseeing future, since it requires manual input.

I'll probably re-add it once I'm not so furiously dropping changes :)

Cheers,
Gus
