### ISSUE TITLE
FPC source 3.0.2 is not used when using LAZ_VER=1.6.2

### ISSUE THREAD

**Issue by gcarreno** [nielsAD/travis-lazarus#11]
Hey there,

As I mentioned on Issue #10 I'm using your very good work.

I've had to comment out any mention of LAZ_VER=1.6.2 from [`.travis.yml`](https://github.com/gcarreno/laz-qBitTorrent-WebUI/blob/master/.travis.yml) because when it compiles I suspect it's not using the source from [`fpc-src_3.0.2-170225_amd64.deb`](http://mirrors.iwi.me/lazarus/releases/Lazarus%20Linux%20amd64%20DEB/Lazarus%201.6.4).

I noticed this because I'm using `fcl-json/jsonscanner.pp` to have access to `TJSONOptions`. This was only introduced recently-ish: From a not so deep search, somewhere near Aug 2015.

The fpc source from the `fpc-src.2.x.deb` does not have `TJSONOptions` and it seems, that whatever version of `lazbuild` it uses to compile, it's always using the source from the dist deb package. At least that's my assessment of it, I could be very wrong.

Hope I'm making sense. It makes sense in my head and it's a bit hard to explain.

How can we make sure fpc uses the source from the mirror download?

Cheers,  
Gus

**Comment by nielsAD** [comment]
To verify which FreePascal version a build is using, view its logs. You'll probably find something along the lines of `Free Pascal Compiler version 3.0.0 [2015/12/05] for x86_64`.

The Lazarus project releases packages with a specific FPC version tied to it. `Lazarus 1.6.2` uses `FPC 3.0.0`. `Lazarus 1.6.4` uses `FPC 3.0.2`, but the DEB package for this release is [faulty](https://travis-ci.org/nielsAD/travis-lazarus/builds/207100260), so you'd probably have to wait a bit before using that.

**Comment by gcarreno** [comment]
Hi Niels,

As I was afraid, I didn't explain myself enough to convey my message...

The problem is not with the compiler, that's fine. The logs show exactly what you mentioned: 3.0.0.

The issue is with the source package. If you open up the DEB fpc-src files for `version 2.6.4(150228)` and `version 3.0.2(170225)` from the site [mirrors.iwi.me](http://mirrors.iwi.me/lazarus/releases/) and compare `packages/fcl-json/jsonscanner.pp` you will notice that `TJSONOptions` is present in that second package.

None the less, when Travis tries to compile my project it errors out with `joUTF8 not found`.

So, I'm assuming it's downloading the `fpc-src_3.0.2-170225_amd64.deb` from [mirrors.iwi.me](http://mirrors.iwi.me/lazarus/releases/) but it's not using it.

How do I test this theory?

Many thanks in advance for your precious time looking at my reports!

Cheers,
Gus

**Comment by gcarreno** [comment]
Hey Niels,

Just a bit more info on this:

I was able to get around this by doing this:
```Pascal
{$IFDEF VER3_1_1}
  jParser := TJSONParser.Create(slJSON.Text, [joUTF8, joIgnoreTrailingComma]);
{$ELSE}
  jParser := TJSONParser.Create(slJSON.Text, True);
{$ENDIF}
```

I still need to get that IFDEF with >=3.1.1 so it makes sense for the future. ATM this was a quickfix that worked.

Before it worked I tried `{$IFDEF VER3}` and that blew up in my face.

For all of what I've said and experimented is why I'm suspecting that fpc 3.0.0 is not using the fpr-src package on the mirros, but the default fpc-src package on the ubuntu repo.

Cheers,
Gus

**Comment by gcarreno** [comment]
Hi Niels,

Hummmm, ok, I got my my versions all mixed up :(

I'm closing this because I realized I compared contents from Laz 1.4.4 and Laz 1.6.4 NOT 1.6.2

In fact fpc-src 3.0.0 does NOT have `JSONOptions`.

It appears in fpc-src 3.0.2.

I probably should get my version in order before shooting my mouth off and for that I deeply apologise!

Thanks for all your answers!!

Cheers,
Gus
