### ISSUE TITLE
fpc only mode

### ISSUE THREAD

**Issue by benibela** [nielsAD/travis-lazarus#12]
I try to keep my projects fpc only, so it is a waste of resources to download/install of Lazarus for every build.

It could be like you write FPC_VER=xx rather than LAZ_VER in the travis file, and then it downloads the corresponding fpc and calls ppc..

**Comment by daar** [comment]
I have the same issue. I am working myself also on an example doing an FPC only build.

**Comment by nielsAD** [comment]
Yes, I can see how this would be useful. I don't think FreePascal offers official DEB packages, so it would have to be handled a bit differently compared to the current workflow for Lazarus.

I will not add this myself, but I am open to pull requests implementing this!

**Comment by benibela** [comment]
> I don't think FreePascal offers official DEB packages

The python could know the lazarus version for the fpc and then download one of those

http://mirrors.iwi.me/lazarus/releases/Lazarus%20Linux%20amd64%20DEB/Lazarus%201.4/fpc_2.6.4-150228_amd64.deb
http://mirrors.iwi.me/lazarus/releases/Lazarus%20Linux%20amd64%20DEB/Lazarus%201.6/fpc_3.0.0-151205_amd64.deb
http://mirrors.iwi.me/lazarus/releases/Lazarus%20Linux%20amd64%20DEB/Lazarus%201.8.0RC5/fpc_3.0.4-rc1_amd64.deb

Or perhaps someone has a PPA. I have only understood the trivial case so far https://github.com/benibela/bbutils/blob/master/.travis.yml

**Comment by nielsAD** [comment]
Ah, yes, that could be an idea! Although it would be limited to the FPC versions that ship with Lazarus, it would be relatively easy to add and should suffice for most cases.

**Comment by benibela** [comment]
Travis has started to support Ubuntu Bionic which has fpc3.0.4, which probably solves this issue for now
