### ISSUE TITLE
CircleCI, AppVeyor

### ISSUE THREAD

**Issue by benibela** [nielsAD/travis-lazarus#15]
Do you have any plans adding more CI services?

**Comment by nielsAD** [comment]
Not at the moment. Is it worth considering other services?

**Comment by benibela** [comment]
AppVeyor at least has Windows installed, so it would be much easier to configure than wine

**Comment by nielsAD** [comment]
I have no plans on adding other services at the moment, but I'm open to pull requests that add support.
