### ISSUE TITLE
Travis Support for Windows

### ISSUE THREAD

**Issue by Xor-el** [nielsAD/travis-lazarus#18]
Hi, @nielsAD .
First of all, I must say thank you for what you did with figuring out how to add travis support for FPC.
Recently, Travis added official support for [Windows](https://blog.travis-ci.com/2018-10-11-windows-early-release) meaning we can do away with wine.
while this is good news, unfortunately am not that good with scripting things so it would be nice if you can add support for Windows (without Wine) in your scripts please.
Thanks and hope to hear from you soon.

Regards.

**Comment by r3code** [comment]
take a look https://github.com/GerryFerdinandus/travis-lazarus/commit/99140c56d6e38388c38c11cdcfd68a77e667b5db
