### ISSUE TITLE
The verify question in http://forum.lazarus.freepascal.org/index.php?action=register2 are too hard

### ISSUE THREAD

**Issue by ghost** [nielsAD/travis-lazarus#2]
Hi,

Glad to see http://forum.lazarus.freepascal.org/index.php?topic=29957.0 and know you use Wine for testing. I tried to register an account but the verification questions are really too hard for me...

BTW I'm also trying similar things: https://github.com/fracting/wine-fracting/wiki/MSYS2-on-Wine#build-status

**Comment by nielsAD** [comment]
Hi @fracting,

Thanks for your interest :) What specific problem do you have with the registration process?

There are three verification questions:

| Question | Answer |
| --- | --- |
| `Not Defined Yet:` | (captcha image) type in the letters formed in the image |
| `Lazarus spelled backwards:` | Answer: `surazaL` |
| `1+2= (answer in text):` | Answer: `three` |
