### ISSUE TITLE
Laz 1.6 and FPC 3.0 supported ?

### ISSUE THREAD

**Issue by ghost** [nielsAD/travis-lazarus#4]
I guess it 's not the case yet. Could you add them ?

**Comment by nielsAD** [comment]
Thanks :)

**Comment by ghost** [comment]
Thx but script fails because of an invalid link:

http://mirrors.iwi.me/lazarus/releases/Lazarus%20Linux%20amd64%20DEB/Lazarus%201.6.0

see here for more details:

https://travis-ci.org/BBasile/Coedit/jobs/110383650

**Comment by nielsAD** [comment]
Use 1.6 instead of 1.6.0 (you can view the available releases [here](http://mirrors.iwi.me/lazarus/releases/Lazarus%20Linux%20amd64%20DEB/)).

**Comment by ghost** [comment]
Right, this time it's ok. Further problems are unrelated to your scripts. Thx again.
